// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA66AuMKMYlM7fzbKShMqs59MAB48fW-WY',
    appId: '1:379899858847:web:e5ced745c0efd4a436f7aa',
    messagingSenderId: '379899858847',
    projectId: 'dinebook-68fcd',
    authDomain: 'dinebook-68fcd.firebaseapp.com',
    storageBucket: 'dinebook-68fcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASgvKdGbBycCMaPAZYJ_iHynOIMZ2Ocs',
    appId: '1:379899858847:android:457a2f297c5015c736f7aa',
    messagingSenderId: '379899858847',
    projectId: 'dinebook-68fcd',
    storageBucket: 'dinebook-68fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslL8eSPFxjEEjfoTeeHREUwPz9WN_rFA',
    appId: '1:379899858847:ios:d3a37954ed8dcb1936f7aa',
    messagingSenderId: '379899858847',
    projectId: 'dinebook-68fcd',
    storageBucket: 'dinebook-68fcd.firebasestorage.app',
    iosBundleId: 'com.example.dinebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAslL8eSPFxjEEjfoTeeHREUwPz9WN_rFA',
    appId: '1:379899858847:ios:d3a37954ed8dcb1936f7aa',
    messagingSenderId: '379899858847',
    projectId: 'dinebook-68fcd',
    storageBucket: 'dinebook-68fcd.firebasestorage.app',
    iosBundleId: 'com.example.dinebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA66AuMKMYlM7fzbKShMqs59MAB48fW-WY',
    appId: '1:379899858847:web:ab63edddf354cd0236f7aa',
    messagingSenderId: '379899858847',
    projectId: 'dinebook-68fcd',
    authDomain: 'dinebook-68fcd.firebaseapp.com',
    storageBucket: 'dinebook-68fcd.firebasestorage.app',
  );

}